#ifndef DEFAULTLIBRARY_VERSION_H
#define DEFAULTLIBRARY_VERSION_H

#define DEFAULTLIBRARY_VERSION 20190330

#define DEFAULTLIBRARY_VERSION_YEAR ((int)(DEFAULTLIBRARY_VERSION/10000))
#define DEFAULTLIBRARY_VERSION_MONTH ((int)((DEFAULTLIBRARY_VERSION%10000)/100))
#define DEFAULTLIBRARY_VERSION_DAY ((int)DEFAULTLIBRARY_VERSION%100)

#endif // DEFAULTLIBRARY_VERSION_H
